apiVersion: skaffold/v2beta6
kind: Config

build:
  local:
    useDockerCLI: true
  artifacts:
    - image: gcr.io/hilltop-285223/hilltop-web
      context: web
    - image: gcr.io/hilltop-285223/hilltop-mailer
      context: mailer
    - image: gcr.io/hilltop-285223/hilltop-flowlauncher
      context: flowlauncher
    - image: gcr.io/hilltop-285223/hilltop-rest-api
      context: rest-api
    - image: gcr.io/hilltop-285223/hilltop-api
      context: web
      docker:
        dockerfile: /src/api/Dockerfile

deploy:
  kubectl:
    manifests:
      - web/k8s/web/*
      - web/k8s/api/*
      - web/k8s/webhook/*
      - mailer/k8s/*
      - flowlauncher/k8s/*

profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubectl:
        manifests:
          - postgres/k8s/dev/*
          - web/k8s/web/*
          - web/k8s/webhook/*
          # - web/k8s/api/*
          - mailer/k8s/*
          - flowlauncher/k8s/*
          - rest-api/k8s/*
    build:
      local:
        push: false
        useDockerCLI: true
      artifacts:
        - image: gcr.io/hilltop-285223/hilltop-web
          context: web
          docker:
            buildArgs:
              ENV: development
        - image: gcr.io/hilltop-285223/hilltop-rest-api
          context: ./
          docker:
            dockerfile: /rest-api/Dockerfile
        - image: gcr.io/hilltop-285223/hilltop-mailer
          context: mailer
          docker:
            buildArgs:
              ENV: development
        - image: gcr.io/hilltop-285223/hilltop-flowlauncher
          context: flowlauncher
          docker:
            buildArgs:
              ENV: development
        # - image: gcr.io/hilltop-285223/hilltop-api
        #   context: web
        #   docker:
        #     dockerfile: /src/api/Dockerfile
        - image: gcr.io/hilltop-285223/hilltop-webhook
          context: web
          docker:
            dockerfile: /src/webhook/Dockerfile
