apiVersion: skaffold/v2beta6
kind: Config

build:
  local:
    useDockerCLI: true
  artifacts:
    - image: gcr.io/hilltop-285223/hilltop-web
      context: web
    - image: gcr.io/hilltop-285223/hilltop-mailer
      context: mailer
    - image: gcr.io/hilltop-285223/hilltop-flowlauncher
      context: flowlauncher
    - image: gcr.io/hilltop-285223/hilltop-api
      context: web
      docker:
        dockerfile: /src/api/Dockerfile

deploy:
  kubectl:
    manifests:
      - web/k8s/*
      - mailer/k8s/*
      - flowlauncher/k8s/*
      - redis/k8s/*
      - postgres/k8s/prod/*

profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubectl:
        manifests:
          - postgres/k8s/dev/*
          - web/k8s/*
          - mailer/k8s/*
          - flowlauncher/k8s/*
          - redis/k8s/*
    build:
      local:
        push: false
        useDockerCLI: true
      artifacts:
        - image: gcr.io/hilltop-285223/hilltop-web
          context: web
          docker:
            buildArgs:
              ENV: development
        - image: gcr.io/hilltop-285223/hilltop-mailer
          context: mailer
          docker:
            buildArgs:
              ENV: development
        - image: gcr.io/hilltop-285223/hilltop-flowlauncher
          context: flowlauncher
          docker:
            buildArgs:
              ENV: development
        - image: gcr.io/hilltop-285223/hilltop-api
          context: web
          docker:
            dockerfile: /src/api/Dockerfile
