apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  ports:
    - port: 8000
  selector:
    app: webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: gcr.io/hilltop-285223/hilltop-webhook
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: redis_url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database_url
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: aws_secret_access_key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: s3_bucket
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: auth0_domain
            - name: API_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: api_identifier
