apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 4000
  type: LoadBalancer
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: hilltop-server
          ports:
            - containerPort: 4000
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: redis_url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: database_url
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: aws_secret_access_key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: s3_bucket
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: auth0_domain
            - name: API_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: api_identifier
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 7777
  type: LoadBalancer
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: hilltop-api
          ports:
            - containerPort: 7777
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: redis_url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: database_url
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: aws_secret_access_key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: s3_bucket
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: auth0_domain
            - name: API_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: api_identifier
