apiVersion: v1
kind: Service
metadata:
  name: flowlauncher
spec:
  ports:
    - port: 5000
  type: LoadBalancer
  selector:
    app: flowlauncher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowlauncher
spec:
  selector:
    matchLabels:
      app: flowlauncher
  template:
    metadata:
      labels:
        app: flowlauncher
    spec:
      containers:
        - name: flowlauncher
          image: gcr.io/hilltop-285223/hilltop-flowlauncher
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: flowlaunch-secrets
                  key: redis_url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database_url
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: flowlaunch-secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: flowlaunch-secrets
                  key: aws_secret_access_key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: flowlaunch-secrets
                  key: s3_bucket
