apiVersion: v1
kind: Service
metadata:
  name: mailer
spec:
  ports:
    - port: 6666
  type: LoadBalancer
  selector:
    app: mailer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
spec:
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: mailer
          image: hilltop-mailer
          ports:
            - containerPort: 6666
          env:
            - name: AWS_ACCESS_KEY
              value: AKIAZNFWS7JQWWXGVLFK
            - name: REDIS_URL
              value: redis://h:p393a70f1ea5a26afb1e6ab8ff54e768c708a40e8e3b929ec5cdb421b91943114@ec2-34-239-221-186.compute-1.amazonaws.com:7019
            - name: AWS_SECRET_ACCESS_KEY
              value: cV03fjelSLEBJNvgNeVgjbe3KyIYZAl7YLpDTVzN
