apiVersion: v1
kind: Service
metadata:
  name: mailer
spec:
  ports:
    - port: 6666
  type: LoadBalancer
  selector:
    app: mailer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
spec:
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: mailer
          image: gcr.io/hilltop-285223/hilltop-mailer
          ports:
            - containerPort: 6666
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: redis_url
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: aws_secret_access_key
